force-app/main/default/objects/Note__c/Note__c.object-meta.xml
<CustomObject>
    <label>Note</label>
    <nameField>
        <displayFormat>NOTE-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Note__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <label>Title</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/NoteWrapper.cls
global class NoteWrapper{

    @AuraEnabled public String id;
    @AuraEnabled public String data;
    @AuraEnabled public String title;

    public NoteWrapper(Note__c note) {
        this.id = note.Id;
        this.data = note.Data__c;
        this.title = note.Title__c;
    }
    
    public Note__c getObject() {
        Note__c note = new Note__c();
        note.Id = this.id;
        note.Data__c = this.data;
        note.Title__c = this.title;
        return note;
    }

    public static NoteWrapper parse(String jsonString) {
        return (NoteWrapper) JSON.deserialize(jsonString, NoteWrapper.class);
    }
}